"""cnpj unique

Revision ID: 30d8a29831b3
Revises: 56fc1257b8bf
Create Date: 2026-08-29 17:12:26.465916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30d8a29831b3'
down_revision: Union[str, Sequence[str], None] = '56fc1257b8bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'empresa', ['cnpj'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'empresa', type_='unique')
    # ### end Alembic commands ###
