"""adiciona deleted_at em users e company

Revision ID: 56fc1257b8bf
Revises: 6ae4239690db
Create Date: 2026-08-28 18:47:31.011640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56fc1257b8bf'
down_revision: Union[str, Sequence[str], None] = '6ae4239690db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresa', sa.Column('ativo', sa.Boolean(), nullable=False))
    op.add_column('empresa', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('usuario', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'deleted_at')
    op.drop_column('empresa', 'deleted_at')
    op.drop_column('empresa', 'ativo')
    # ### end Alembic commands ###
