"""cria branco

Revision ID: 6ae4239690db
Revises: 
Create Date: 2026-08-27 12:15:51.614434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ae4239690db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_chamado',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('valor', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_chamado_id'), 'categorias_chamado', ['id'], unique=False)
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_empresa', sa.String(length=100), nullable=False),
    sa.Column('cnpj', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresa_id'), 'empresa', ['id'], unique=False)
    op.create_table('enum_perfis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('valor', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('valor')
    )
    op.create_index(op.f('ix_enum_perfis_id'), 'enum_perfis', ['id'], unique=False)
    op.create_table('prioridade_chamado',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('valor', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prioridade_chamado_id'), 'prioridade_chamado', ['id'], unique=False)
    op.create_table('status_chamado',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('valor', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_chamado_id'), 'status_chamado', ['id'], unique=False)
    op.create_table('tipos_evento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('valor', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_evento_id'), 'tipos_evento', ['id'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('perfil', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('tentativas_login', sa.Integer(), nullable=False),
    sa.Column('tempo_bloqueado', sa.DateTime(), nullable=True),
    sa.Column('vezes_bloqueado', sa.Integer(), nullable=True),
    sa.Column('token_verificacao', sa.String(length=255), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['perfil'], ['enum_perfis.valor'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuario_id'), 'usuario', ['id'], unique=False)
    op.create_table('chamado',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('prioridade_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('data_hora_fechamento', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_chamado.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['prioridade_id'], ['prioridade_chamado.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status_chamado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chamado_id'), 'chamado', ['id'], unique=False)
    op.create_table('historico_chamado',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chamado_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo_evento_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chamado_id'], ['chamado.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['tipo_evento_id'], ['tipos_evento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_chamado_id'), 'historico_chamado', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historico_chamado_id'), table_name='historico_chamado')
    op.drop_table('historico_chamado')
    op.drop_index(op.f('ix_chamado_id'), table_name='chamado')
    op.drop_table('chamado')
    op.drop_index(op.f('ix_usuario_id'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_tipos_evento_id'), table_name='tipos_evento')
    op.drop_table('tipos_evento')
    op.drop_index(op.f('ix_status_chamado_id'), table_name='status_chamado')
    op.drop_table('status_chamado')
    op.drop_index(op.f('ix_prioridade_chamado_id'), table_name='prioridade_chamado')
    op.drop_table('prioridade_chamado')
    op.drop_index(op.f('ix_enum_perfis_id'), table_name='enum_perfis')
    op.drop_table('enum_perfis')
    op.drop_index(op.f('ix_empresa_id'), table_name='empresa')
    op.drop_table('empresa')
    op.drop_index(op.f('ix_categorias_chamado_id'), table_name='categorias_chamado')
    op.drop_table('categorias_chamado')
    # ### end Alembic commands ###
