"""unique in categories

Revision ID: 7bbebfa268e2
Revises: 30d8a29831b3
Create Date: 2026-08-31 08:56:39.802712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bbebfa268e2'
down_revision: Union[str, Sequence[str], None] = '30d8a29831b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'categorias_chamado', ['valor'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categorias_chamado', type_='unique')
    # ### end Alembic commands ###
