from app.models.usuario_model import Usuario
from app.models.categorias_chamado_model import CategoriasChamado
from app.models.chamado_model import Chamado
from app.models.empresa_model import Empresa
from app.models.enum_perfis_model import EnumPerfis
from app.models.historico_chamado_model import HistoricoChamado
from app.models.prioridade_chamado_model import PrioridadeChamado
from app.models.status_chamado_model import StatusChamado
from app.models.tipos_eventos_model import TiposEvento